### ISSUE TITLE
sanitize input when user attempts to add a role

### ISSUE THREAD

**Issue by Ramsfield** [CodeMastr3/hackbot#10]
If a user says:
!add CSCI-340
it should be interpreted as
!add csci-340

**Comment by CodeMastr3** [comment]
While we could for example to lower the input what about for example allClass with a capital C we could just make all assignable roles lowercase though

**Comment by CodeMastr3** [comment]
Or just make an exception for that role when we need to. I'll fix this with this solution in mind
